### ISSUE TITLE
Adding the credentials.json File to gitignore File

### ISSUE THREAD

**Issue by rodriguez03** [GatorEducator/cellveyor#26]
Adding the credentials.json to the gitignore file will allow other users to input their own credentials without sharing it to everyone. It will also enable GitHub to not restrict developers to continue editing on this project.

**Comment by gkapfham** [comment]
This is a good point @rodriguez03, thanks for sharing it! It is important to note that there may be some other types of files that also need to be added to the `.gitignore` file so as to ensure that they are not committed into the project's GitHub repository.

**Comment by rodriguez03** [comment]
.gitignore file modified!
