### ISSUE TITLE
ReadMe Update

### ISSUE THREAD

**Issue by KevenDuverglas** [GatorEducator/cellveyor#3]
The ReadMe needs more documentation and needs to be up to par(like chasten).

- Make a Logo for Cellveyor

**Comment by hayleepierce** [comment]
### List of Things that Should be in the README
- Command examples
- References to similar tools
- References to frameworks and libraries used in tool
- References a publicly available Google Sheet for testing purposes
- Give examples of regular expressions that match Google Sheet columns
- How to securely access GitHub through token creation
- How to securely access Google Sheets through token creation

**Comment by gyamfi01** [comment]
Jason will be helping out with this

**Comment by gkapfham** [comment]
Hello @KevenDuverglas and @gyamfi01, when you have time, please share a status update concerning your completion of work on the README file!

@hayleepierce, thanks for sharing the details that need to be included inside of the README. One point that I wanted to stress about writing the content in the README is that we need to be absolutely sure that we do not actually give a real example of any API key inside of the documentation as this would be a security vulnerability and thus something we absolutely must avoid. Thanks for your attention to detail about this important issue!

**Comment by hayleepierce** [comment]
@KevenDuverglas, @gyamfi01, and @naboni07 be sure to collaborate with each other. Determine whose fork you will be working in and add the other team members as collaborators. @naboni07 created the logo and it needs to be added to the README.
