### ISSUE TITLE
Implement basic GitHub Actions that installs dependencies and runs program

### ISSUE THREAD

**Issue by EvanNelson04** [GatorEducator/cellveyor#9]

**Comment by gkapfham** [comment]
Hello @EvanNelson04, this is an important feature to add.

I should also point out that we need to setup a (at least partially) automated system that makes it possible to publish the project to the Python Package Index.

**Comment by hayleepierce** [comment]
@gkapfham, Keven has been working on this and has even created a PR (#24). I tried to add him to this issue as an assignee but for some reason, I can't?

**Comment by hayleepierce** [comment]
**GitHub Actions Should Do the Following:**

- _Running the tool in GitHub Actions will require access to a GitHub token_
- Installs dependencies and runs program
- Runs linting and testing tasks
- Performs a tool release
- Confirms that the tool works correctly on all of the major operating systems
- Confirms that the test suite passes on all of the major operating systems

**Comment by gkapfham** [comment]
Hi @hayleepierce, note that this will require us to setup various parts of the tool's use of Poetry. So, we will need to add tasks in the `pyproject.toml` file and then make sure that the various tools are listed as dev dependencies.

Please let me know if there is a way in which I can help with this task as it is important to have a suitable CI setup before we start to merge main features for the tool!
